apiVersion: v1
kind: ConfigMap
metadata:
  name: mediamtx-config
  namespace: mediamtx
data:
  mediamtx.yml: |
    rtmp: yes
    webrtc: yes
    api: yes
    paths:
      all:
        source: publisher