---
apiVersion: v1
kind: Namespace
metadata:
  name: mediamtx
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mediamtx-config
  namespace: mediamtx
  labels:
    app: mediamtx
data:
  mediamtx.yml: |
    server:
      logLevel: info
    rtmp:
      enable: yes
    hls:
      enable: yes
    webrtc:
      enable: yes
    api: yes
    paths:
      all:
        source: publisher
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediamtx
  namespace: mediamtx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediamtx
  template:
    metadata:
      labels:
        app: mediamtx
    spec:
      containers:
        - name: mediamtx
          image: bluenviron/mediamtx:latest
          ports:
            - containerPort: 8554
            - containerPort: 1935
            - containerPort: 8888
            - containerPort: 9997
          volumeMounts:
            - name: config
              mountPath: /mediamtx.yml
              subPath: mediamtx.yml
      volumes:
        - name: config
          configMap:
            name: mediamtx-config
---
apiVersion: v1
kind: Service
metadata:
  name: mediamtx
  namespace: mediamtx
spec:
  type: LoadBalancer
  ports:
    - name: rtsp
      port: 8554
      targetPort: 8554
    - name: rtmp
      port: 1935
      targetPort: 1935
    - name: http
      port: 8888
      targetPort: 8888
    - name: api
      port: 9997
      targetPort: 9997
  selector:
    app: mediamtx
