replicaCount: 1

imagePullSecrets:
  - name: ghcr-secret

service:
  type: ClusterIP
  port: 80

api:
  image:
    repository: ghcr.io/greenbowalabama/launch-lab-api
    tag: latest
    pullPolicy: Always
  port: 5050

ui:
  image:
    repository: ghcr.io/greenbowalabama/launch-lab-ui
    tag: 2c31ce2
    pullPolicy: Always
  port: 80

simulator:
  enabled: false
  image:
    repository: ghcr.io/greenbowalabama/launch-lab
    tag: latest
    pullPolicy: Always
  args:
    - "--mode=replay"
    - "--source=/app/recordings/test_kick.mp4"
  env:
    RTSP_URL: rtsp://192.168.1.226:8554/live/stream

resources: {}

ingress:
  enabled: true
  className: "nginx"  # or your ingress controller class, if set
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: launch-labs.io
      paths:
        - path: /
          pathType: Prefix
  tls: []

config:
  RTSP_URL: rtsp://192.168.1.226:8554/live/stream