replicaCount: 1

imagePullSecrets:
  - name: ghcr-secret

service:
  type: ClusterIP
  port: 80

api:
  env:
    DB_HOST: launch-lab-db.postgres.database.azure.com
    DB_PORT: "5432"
    DB_NAME: launch_lab
    DB_USER: launch_admin
  image:
    repository: ghcr.io/greenbowalabama/launch-lab-api
    tag: latest
    pullPolicy: Always
  port: 5050

ui:
  env:
    VITE_API_URL: https://launch-labs.io/api
  image:
    repository: ghcr.io/greenbowalabama/launch-lab-ui
    tag: latest
    pullPolicy: Always
  port: 80

simulator:
  enabled: false
  image:
    repository: ghcr.io/greenbowalabama/launch-lab
    tag: latest
    pullPolicy: Always
  args:
    - "--mode=replay"
    - "--source=/app/recordings/test_kick.mp4"
  env:
    RTSP_URL: rtsp://192.168.1.226:8554/live/stream

resources: {}

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
  hosts:
    - host: launch-labs.io
      paths:
        - path: /
          pathType: Prefix
          serviceName: launch-lab-prod-ui
          servicePort: 80
        - path: /api
          pathType: Prefix
          serviceName: launch-lab-prod-api
          servicePort: 5050
  tls:
    - hosts:
        - launch-labs.io
      secretName: launch-labs-io-tls

config:
  RTSP_URL: rtsp://192.168.1.226:8554/live/stream