apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app: {{ .Release.Name }}-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-api
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-api
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: launch-lab-api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.api.port }}
          env:
            - name: DB_HOST
              value: {{ .Values.api.env.DB_HOST | quote }}
            - name: DB_PORT
              value: {{ .Values.api.env.DB_PORT | quote }}
            - name: DB_NAME
              value: {{ .Values.api.env.DB_NAME | quote }}
            - name: DB_USER
              value: {{ .Values.api.env.DB_USER | quote }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: RTSP_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: RTSP_URL
          readinessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.api.port }}
            initialDelaySeconds: 5
            periodSeconds: 10