apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ui
  labels:
    app: launch-lab-ui
    {{- include "launch-lab.labels" . | nindent 4 }}
spec:
  imagePullSecrets:
    - name: {{ .Values.imagePullSecrets | first }}
  replicas: 1
  selector:
    matchLabels:
      app: launch-lab-ui
  template:
    metadata:
      labels:
        app: launch-lab-ui
    spec:
      containers:
        - name: ui
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
          ports:
            - containerPort: 80
