apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ui
  labels:
    app: {{ .Release.Name }}-ui
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-ui
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.ui.port }}