# .github/workflows/cd-dev.yml
name: CD - Deploy to Dev Environment

on:
  push:
    branches:
      - dev

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Set up Azure credentials
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Kubeconfig
        run: az aks get-credentials --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }} --overwrite-existing

      - name: Deploy Helm chart to dev
        run: |
          helm upgrade --install launch-lab ./charts/launch-lab \
            --namespace default \
            --set image.tag=dev \
            -f charts/launch-lab/values-dev.yaml
