# .github/workflows/ci.yml
name: CI - Build and Push to GHCR

on:
  push:
    branches:
      - main

env:
  API_IMAGE: ghcr.io/greenbowalabama/launch-lab-api
  UI_IMAGE: ghcr.io/greenbowalabama/launch-lab-ui

jobs:
  build-and-push-api:
    name: Build and Push API
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push API image
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          docker buildx build \
            --file ./api/Dockerfile \
            --tag $API_IMAGE:$SHORT_SHA \
            --tag $API_IMAGE:latest \
            --push \
            ./api

  build-and-push-ui:
    name: Build and Push UI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push UI image
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          docker buildx build \
            --file ./ui/Dockerfile \
            --tag $UI_IMAGE:$SHORT_SHA \
            --tag $UI_IMAGE:latest \
            --push \
            ./ui