# .github/workflows/ci.yml
name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:

env:
  API_IMAGE: ghcr.io/iancarter13/launch-lab-api
  UI_IMAGE: ghcr.io/iancarter13/launch-lab-ui

jobs:
  build-and-push:
    name: Build and Push Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Set image tags
        id: set-tags
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          echo "api_tag=${{ env.API_IMAGE }}:${SHORT_SHA}" >> $GITHUB_OUTPUT
          echo "ui_tag=${{ env.UI_IMAGE }}:${SHORT_SHA}" >> $GITHUB_OUTPUT

      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: ./api
          push: true
          tags: ${{ steps.set-tags.outputs.api_tag }}

      - name: Build and push UI image
        uses: docker/build-push-action@v5
        with:
          context: ./ui
          push: true
          tags: ${{ steps.set-tags.outputs.ui_tag }}