# .github/workflows/ci.yml
name: CI - Build and Push to GHCR

on:
  push:
    branches:
      - main
      - dev

env:
  API_IMAGE: ghcr.io/iancarter13/launch-lab-api
  UI_IMAGE: ghcr.io/iancarter13/launch-lab-ui

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Set image tags
        id: set-tags
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}" | tr '[:upper:]' '[:lower:]')
          echo "api_tag=${API_IMAGE}:${SHORT_SHA}" >> $GITHUB_OUTPUT
          echo "ui_tag=${UI_IMAGE}:${SHORT_SHA}" >> $GITHUB_OUTPUT

      - name: Build and Push API
        uses: docker/build-push-action@v5
        with:
          context: ./api
          push: true
          tags: ${{ steps.set-tags.outputs.api_tag }}

      - name: Build and Push UI
        uses: docker/build-push-action@v5
        with:
          context: ./ui
          push: true
          tags: ${{ steps.set-tags.outputs.ui_tag }}