# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [dev, main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: iancarter13/launch-lab
      UI_IMAGE_NAME: iancarter13/launch-lab-ui

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set image tag based on branch
        id: set-tag
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "tag=latest" >> $GITHUB_OUTPUT
          else
            echo "tag=dev" >> $GITHUB_OUTPUT
          fi

      - name: Build and push backend image
        run: |
          docker build -t $IMAGE_NAME:${{ steps.set-tag.outputs.tag }} .
          docker push $IMAGE_NAME:${{ steps.set-tag.outputs.tag }}

      - name: Build and push UI image
        run: |
          docker build -t $UI_IMAGE_NAME:${{ steps.set-tag.outputs.tag }} ./ui
          docker push $UI_IMAGE_NAME:${{ steps.set-tag.outputs.tag }}
