name: CD - Deploy to Dev Environment

on:
  workflow_run:
    workflows: ["CI - Build and Push to GHCR"]
    types:
      - completed

env:
  CHART_PATH: charts/launch-lab
  RELEASE_NAME: launch-lab-dev
  NAMESPACE: launch-lab-dev
  API_IMAGE: ghcr.io/greenbowalabama/launch-lab-api
  UI_IMAGE: ghcr.io/greenbowalabama/launch-lab-ui

jobs:
  deploy-dev:
    name: Deploy to Dev AKS
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Download triggering commit SHA
        run: |
          echo "COMMIT_SHA=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }} --jq .head_sha)" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout code at triggering commit
        uses: actions/checkout@v4
        with:
          ref: ${{ env.COMMIT_SHA }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context for Dev
        uses: azure/aks-set-context@v3
        with:
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME_DEV }}
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP_DEV }}

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Extract short SHA
        id: set-tags
        run: |
          SHORT_SHA=$(echo "${{ env.COMMIT_SHA }}" | cut -c1-7)
          echo "short_sha=$SHORT_SHA" >> $GITHUB_OUTPUT

      - name: Deploy to Dev using Helm
        run: |
          helm upgrade --install $RELEASE_NAME $CHART_PATH \
            --namespace $NAMESPACE --create-namespace \
            --set api.image.repository=${{ env.API_IMAGE }} \
            --set api.image.tag=${{ steps.set-tags.outputs.short_sha }} \
            --set ui.image.repository=${{ env.UI_IMAGE }} \
            --set ui.image.tag=${{ steps.set-tags.outputs.short_sha }} \
            --set imagePullSecrets[0].name=ghcr-secret