name: CD - Deploy to Dev AKS

on:
  push:
    branches:
      - dev

env:
  CHART_PATH: charts/launch-lab
  RELEASE_NAME: launch-lab-dev
  NAMESPACE: launch-lab-dev
  API_IMAGE: ghcr.io/iancarter13/launch-lab-api
  UI_IMAGE: ghcr.io/iancarter13/launch-lab-ui

jobs:
  deploy-dev:
    name: Deploy to Dev AKS
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Set image tags
        id: set-tags
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          echo "api_tag=${SHORT_SHA}" >> $GITHUB_OUTPUT
          echo "ui_tag=${SHORT_SHA}" >> $GITHUB_OUTPUT

      - name: Set AKS Credentials for Dev
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_DEV }}

      - name: Get AKS Context
        run: |
          az aks get-credentials \
            --name ${{ secrets.AKS_CLUSTER_NAME_DEV }} \
            --resource-group ${{ secrets.AKS_RESOURCE_GROUP_DEV }} \
            --overwrite-existing

      - name: Deploy to Dev using Helm
        run: |
          helm upgrade --install $RELEASE_NAME $CHART_PATH \
            --namespace $NAMESPACE --create-namespace \
            --set image.repository=${{ env.API_IMAGE }} \
            --set image.tag=${{ steps.set-tags.outputs.api_tag }} \
            --set uiImage.repository=${{ env.UI_IMAGE }} \
            --set uiImage.tag=${{ steps.set-tags.outputs.ui_tag }}