name: CD - Deploy to Production

env:
  CHART_PATH: charts/launch-lab
  RELEASE_NAME: launch-lab-prod
  NAMESPACE: launch-lab-prod
  API_IMAGE_REPO: ghcr.io/iancarter13/launch-lab-api
  UI_IMAGE_REPO: ghcr.io/iancarter13/launch-lab-ui

on:
  push:
    branches:
      - main

jobs:
  deploy-prod:
    name: Deploy to Prod AKS
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Set image tags
        id: set-tags
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          echo "API_IMAGE_TAG=${API_IMAGE_REPO}:${SHORT_SHA}" >> $GITHUB_ENV
          echo "UI_IMAGE_TAG=${UI_IMAGE_REPO}:${SHORT_SHA}" >> $GITHUB_ENV

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Kubernetes context
        run: |
          az aks get-credentials --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} \
                                 --name ${{ secrets.AKS_CLUSTER_NAME }} \
                                 --overwrite-existing

      - name: Deploy with Helm
        run: |
          helm upgrade --install $RELEASE_NAME $CHART_PATH \
            --namespace $NAMESPACE --create-namespace \
            --set image.repository=${{ env.API_IMAGE_REPO }} \
            --set image.tag=${{ github.sha }} \
            --set uiImage.repository=${{ env.UI_IMAGE_REPO }} \
            --set uiImage.tag=${{ github.sha }}