# .github/workflows/prod-deploy.yml
name: CD - Deploy to Production

on:
  workflow_run:
    workflows: ["CI - Build and Push to GHCR"]
    types:
      - completed

env:
  CHART_PATH: charts/launch-lab
  RELEASE_NAME: launch-lab-prod
  NAMESPACE: launch-lab-prod
  API_IMAGE: ghcr.io/greenbowalabama/launch-lab-api
  UI_IMAGE: ghcr.io/greenbowalabama/launch-lab-ui

jobs:
  deploy-prod:
    name: Deploy to Prod AKS
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Download triggering commit SHA
        run: |
          echo "COMMIT_SHA=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }} --jq .head_sha)" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout code at triggering commit
        uses: actions/checkout@v4
        with:
          ref: ${{ env.COMMIT_SHA }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context for Prod
        uses: azure/aks-set-context@v3
        with:
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME_PROD }}
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP_PROD }}

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Set image tags
        id: set-tags
        run: |
          SHORT_SHA=$(echo "${{ env.COMMIT_SHA }}" | cut -c1-7)
          echo "api_tag=${API_IMAGE}:${SHORT_SHA}" >> $GITHUB_OUTPUT
          echo "ui_tag=${UI_IMAGE}:${SHORT_SHA}" >> $GITHUB_OUTPUT

      - name: Deploy to Prod using Helm
        run: |
          helm upgrade --install $RELEASE_NAME $CHART_PATH \
            --namespace $NAMESPACE --create-namespace \
            --set image.repository=${{ env.API_IMAGE }} \
            --set image.tag=${{ steps.set-tags.outputs.api_tag }} \
            --set uiImage.repository=${{ env.UI_IMAGE }} \
            --set uiImage.tag=${{ steps.set-tags.outputs.ui_tag }}