# .github/workflows/prod-deploy.yml
name: CD - Deploy to Production

env:
  CHART_PATH: charts/launch-lab
  RELEASE_NAME: launch-lab-prod
  NAMESPACE: launch-lab-prod
  API_IMAGE: ghcr.io/iancarter13/launch-lab-api
  UI_IMAGE: ghcr.io/iancarter13/launch-lab-ui

on:
  push:
    branches:
      - main

jobs:
  deploy-prod:
    name: Deploy to Prod AKS
    runs-on: ubuntu-latest
    environment: production
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Set image tags
        id: set-tags
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          echo "api_tag=${API_IMAGE}:${SHORT_SHA}" >> $GITHUB_OUTPUT
          echo "ui_tag=${UI_IMAGE}:${SHORT_SHA}" >> $GITHUB_OUTPUT

      - name: Deploy with Helm
        run: |
          helm upgrade --install $RELEASE_NAME $CHART_PATH \
            --namespace $NAMESPACE --create-namespace \
            --set image.repository=${{ env.API_IMAGE }} \
            --set image.tag=${{ steps.set-tags.outputs.api_tag }} \
            --set uiImage.repository=${{ env.UI_IMAGE }} \
            --set uiImage.tag=${{ steps.set-tags.outputs.ui_tag }}