# .github/workflows/prod-deploy.yml
name: CD - Deploy to Production

env:
  CHART_PATH: charts/launch-lab
  RELEASE_NAME: launch-lab-prod
  NAMESPACE: launch-lab-prod
  API_IMAGE: ghcr.io/greenbowalabama/launch-lab-api
  UI_IMAGE: ghcr.io/greenbowalabama/launch-lab-ui

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: CI - Build and Push to GHCR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Extract short SHA
        id: sha
        run: echo "short_sha=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Build and push API image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --file ./Dockerfile \
            --tag $API_IMAGE:${{ steps.sha.outputs.short_sha }} \
            --push \
            .

      - name: Build and push UI image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --file ./ui/Dockerfile \
            --tag $UI_IMAGE:${{ steps.sha.outputs.short_sha }} \
            --push \
            ./ui

  deploy-aks:
    name: Provision Prod AKS
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME_PROD }}
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP_PROD }}

  deploy-prod:
    name: Deploy to Prod AKS
    runs-on: ubuntu-latest
    needs: [build-and-push, deploy-aks]
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME_PROD }}
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP_PROD }}

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Extract short SHA
        id: sha
        run: echo "short_sha=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Deploy with Helm
        run: |
          helm upgrade --install $RELEASE_NAME $CHART_PATH \
            --namespace $NAMESPACE --create-namespace \
            --set image.repository=$API_IMAGE \
            --set image.tag=${{ steps.sha.outputs.short_sha }} \
            --set uiImage.repository=$UI_IMAGE \
            --set uiImage.tag=${{ steps.sha.outputs.short_sha }}