name: Scale AKS Up

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Environment (e.g., dev, staging, prod)"
        required: true
        default: dev

jobs:
  scale-up:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Scale GPU pool using script
      run: ./scripts/scale-up.sh ${{ github.event.inputs.env }}
