# .github/workflows/setup-ingress.yml
name: Setup Ingress Controller for AKS

env:
  INGRESS_NAMESPACE: ingress-nginx

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/setup-ingress.yml
      - scripts/install-ingress.sh

jobs:
  setup-ingress:
    name: Install NGINX Ingress Controller
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME_PROD }}
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP_PROD }}

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Install ingress via script
        run: bash scripts/install-ingress.sh
        
      - name: Verify ingress controller pods
        run: kubectl get pods -n $INGRESS_NAMESPACE

      - name: Get public IP
        run: |
          kubectl get svc ingress-nginx-controller -n $INGRESS_NAMESPACE -o jsonpath='{.status.loadBalancer.ingress[0].ip}'